content:
  - name: posts
    label: Posts
    path: src/posts
    type: collection
    fields: 
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
        options:
          time: true
      - name: body
        label: Body
        type: rich-text
        