content:
  - name: posts
    label: Posts
    path: src/posts
    type: collection
    fields: 
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Date
        type: date
        options:
          time: true
          format: YYYY-MM-DDThh:mm:ssTZD
      - name: body
        label: Body
        type: rich-text
        