media: src/images
content:
  - name: posts
    label: Posts
    path: src/posts
    type: collection
    view:
      fields: [ title, draft, date ]
    fields: 
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string }
      - { name: date, label: Date, type: date, options: { time: true }}
      - { name: draft, label: Draft, type: boolean }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: body, label: Body, type: rich-text }
        